# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pack the APP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - name: Compress the JS
    - run: npm install uglify-js -g
    - run: uglifyjs --compress --mangle -- landEX.lxl.js -o landEX.lxl.min.js
    - name: Moving 
    - run: mkdir dist
    - run: mv landEX.lxl.min.js dist/
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "LandEX_Package"
        path: dist
